### ISSUE TITLE
[Python] Crashed after a while, i suppose because exception occurred before HTTP Error code came

### ISSUE THREAD

**Issue by K4r0qtuYNE5G4qgZ** [SteamDatabase/SalienCheat#83] opened 2018-06-24 02:16 UTC
03:52:24 | -- GET  ITerritoryControlMinigameService/GetPlanet     ('Connection aborted.', BadStatusLine("''",))
Planet #8           88% |##################################################7       |  1:43:45

Zone #77 - Easy     40% |#######################4                                  |    35:41Traceback (most recent call last):
  File "cheat.py", line 533, in <module>
    game.refresh_planet_info()
  File "cheat.py", line 181, in refresh_planet_info
    self.planet = self.get_planet(self.player_info['active_planet'])
  File "cheat.py", line 190, in get_planet
    retry=True,
  File "cheat.py", line 144, in sget
    if resp.status_code >= 500:
UnboundLocalError: local variable 'resp' referenced before assignment

**Comment by DmACKGL** [comment] 2018-06-24 02:49
#82

**Comment by dusekdan** [comment] 2018-06-24 02:49
This is probably a duplicate of #82.

**Closed** 2018-06-24 04:46 UTC
